### ISSUE TITLE
Déplacement des icones sur le portail....

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-portail#102]
tout marche sauf les icones qui se trouvent a droite du portail voir photo
![bug_deplacement_des_icones_portail](https://cloud.githubusercontent.com/assets/9947536/8851516/2fc76a86-3150-11e5-85a8-934ed209b072.png)

**Comment by cycojesus** [comment]
arrive quand la tuile est plus haute que large (ou plus ou moins ça)

**Comment by Bruno-o** [comment]
comprend pas bien dsl. J'ai oublié de préciser que ma souris est sur le carré blanc...

**Comment by cycojesus** [comment]
Je précise juste un truc que j'ai remarqué pour quand je corrigerais plus tard. Ça reste un vrai bug valide
