### ISSUE TITLE
Problème d'encodage lors de la modification du profil utilisateur

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-portail#114]
Dans le portail, si j'édite mon profil et que je mets des accents dans le prénom (par exemple). J'obtiens une requête PUT https://v3.laclasse.com/portail/api/user?date_naissance=1970-01-01T00:00:00.000Z&nom=Levallois&prenom=Pierre-Gilles+%C3%A7%C3%A8%26@%C3%A0&sexe=M

Le problème c'est que dans la base de donnée le prénom est enregistré encodé au format URL:

mysql> select prenom from user where id_ent='VAA60001';
+--------------------------------------+
| prenom                               |
+--------------------------------------+
| Pierre-Gilles%20%C3%A7%C3%A8&@%C3%A0 |
+--------------------------------------+

Et évidemment dans les services de l'annuaire (ex: etab/:etab/users) on retrouve ce mauvais encodage.

Le truc étrange c'est que dans le portail (coin en haut à gauche) il est correctement affiché. Il y a peut être du coup une double erreur d'encodage.

**Comment by pvincent4** [comment]
Je confirme, ça m'a bloqué l'authentification CAS CCN depuis ton compte. 
Une fois bien réécrit ça passe.
Il faut que je rajoute des tests à mon niveau.

**Comment by pvincent4** [comment]
Je confirme, ça m'a bloqué l'authentification CAS CCN depuis ton compte. 
Une fois bien réécrit ça passe.
Il pas réglé de votre côté il faut que je rajoute des tests.
