### ISSUE TITLE
tout cassé sur Safari

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-portail#130]

**Comment by cycojesus** [comment]
testé non reproduit sur Safari 8.0.3

**Comment by Pilooz** [comment]
Testé er reproduit sur Safari 9.0 sous MacOSX El Capitan
![bug-safari](https://cloud.githubusercontent.com/assets/1265220/11183415/cd88539e-8c71-11e5-8ff7-6fd78d79c57f.png)

**Comment by cycojesus** [comment]
fixed for non-modification mode (normal users)
