### ISSUE TITLE
Rendre possible pour tous les profils la modification de son mot de passe par l'utilisateur lui-même

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-portail#162]
l'affichage semble aléatoire quand on clique sur son nom pour avoir son profil et le modifier, la modification de son mot de passe apparaît parfois mais pas tout le temps. L'idéal serait que chacun puisse avoir la possibilité de le modifier.

**Comment by cycojesus** [comment]
Si la tuile 'Téléservices académiques' est présente on présume que l'utilisateur se connecte par l'authentification académique et n'a pas besoin de gérer son mot de passe laclasse
