### ISSUE TITLE
Test V3 - 2016 : Affichage des tuiles en fonction des profils de l'utilisateur et des droits d'accès au tuile

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-portail#165]
Pour un utilisateur multiprofils, par exemple personnel de direction et personnel de collectivité territoriale, après avoir accédé par exemple au service documents en tant que personnel de direction, si l'utilisateur modifie son profil à partir du bandeau du portail accessible depuis la tuile documents, la tuile continue de s'afficher alors que le personnel de collectivité territoriale n'accède pas à ce service.

**Comment by TestsCGI** [comment]
Pour l'exemple ci-dessus, l'application documents reste disponible une fois le changement de profil effectué. Par contre lorsqu'on revient sur le portail la tuile Documents n'est plus disponible

**Comment by cycojesus** [comment]
tenir compte de la conf 'hidden' par profil lors du rechargement de la page app-wrapper
