### ISSUE TITLE
Clarifier, améliorer la popup de changement de mot de passe

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-portail#167]

**Comment by heleroy** [comment]
Notamment, lorsque l'on ne saisit pas le même mot de passe dans le second champ de nouveau mdp, le bouton enregistré disparaît. Il reste apparent  si le mdp est bien le même que dans le premier champ. Celà ne se produit que sur la fenêtre de changement du mdp par défaut.
![capture du 2016-08-22 10-44-23](https://cloud.githubusercontent.com/assets/7963908/17848867/2b72bbd2-6856-11e6-9d6c-aa5aba49d9ad.png)
