### ISSUE TITLE
refonte page stats

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-portail#170]

**Comment by TestsCGI** [comment]
Suite à notre point de ce jour, refonte de la page des stats en 2 temps :
(1) Pour le 18/10
**Evolution des stats existantes**, à savoir :
- Répartition sur une période donnée (jour / semaine / mois / année) du nombre de clics par établissement --> à rendre plus lisible + ajouter le nombre d'applications utilisées par établissement
- Répartition sur une période donnée du nombre de clics par application --> à décliner par établissement + enlever les applications portail et sans libellé
- Répartition sur une période donnée du nombre de clics par profil --> à décliner par établissement
**Ajout d'une nouvelle stat** : visiteurs uniques, c'est à dire le nombre de visiteurs compte tenu du nombre de comptes utilisateurs par établissement
**Évolutions supplémentaires ** : accès aux stats par les personnels de direction pour leur établissement uniquement + évolution des stats de fréquentation hebdomadaire et quotidienne à décliner par établissement

(2) Puis mise en oeuvre dès que possible de ces mêmes stats pour un suivi mensuel de leur évolution par établissement, à savoir :
- Evolution du nombre de clics / établissement
- Evolution du nombre de visiteurs uniques / établissement
- Evolution du nombre de clics / application / établissement
- Evolution du nombre d'utilisateur / profil / établissement

Remarque : ces stats d'usage ne prennent pas en compte les accès directs aux applications messagerie et blog, c'est à dire l'utilisation de ces applications sans passage par le portail.
