### ISSUE TITLE
Tuile Webmail non visible

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/service-portail#185]
Pour l'utilisateur eleschiera. Il était Personnel de direction... sans email laclasse.com. Il rajoute la tuile Webmail. Il la voit apparaître mais elle disparait à la  prochaine connexion.

Si on lui ajoute une email laclasse.com. C'est pas mieux. Même si on remet la tuile webmail.

Problème donc à qualifier et corriger.

**Comment by cycojesus** [comment]
l'utilisateur a créé son adresse email laclasse en la typant « Autre »
