### ISSUE TITLE
Sur Chrome, lorsque l'on se connecte sur l'ENT, on ne tombe pas sur le portail car dirigé vers aucun service

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-portail#194]
Si je me connecte depuis www.laclasse.com, j'arrive sur la page bleue qui me dit "connexion réussie" et me propose de me déconnecter et de fermer mon navigateur. Ce n'est pas logique. Je devrais arriver sur le portail. Pour arriver au portail je suis obligée de supprimer tout ce qui suit www.laclasse.com sur l'url inscrite dans la barre d'adresse.

**Comment by dlacroix** [comment]
c'est un problème de LaclasseService. Normalement corrigé

**Comment by heleroy** [comment]
En effet, je confirme que c'est résolu.
