### ISSUE TITLE
(amélioration) authentification par type de profil

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-portail#210]
Les enseignants de la formation DANE font remarquer qu'il est plus intuitif d'avoir une entrée directe par le type de profil et non pas par le type de compte (laclasse/académie). 
Peut-on directement reconnaître un utilisateur quelque soit son mail de connexion, sans le faire choisir ?

**Comment by gwenhael-le-moine** [comment]
c'est un choix offert à l'utilisateur et pas un aiguillage suivant le profil.
