### ISSUE TITLE
 [Stats] bug affichage page depuis admin

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-portail#214]
Page not found (et pas du tout erreur 404.. 
Test avec mon compte crizzo2
![stats](https://user-images.githubusercontent.com/24314392/39999219-d3ef9262-5788-11e8-92e6-01390f2b33b3.PNG)

**Comment by gwenhael-le-moine** [comment]
[index.html](https://www.laclasse.com/portail/stats/index.html) + application réparée
