### ISSUE TITLE
Indiquer l'impossibilité d'éditer les ressources pour les non super admin

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-portail#215]
Dans l'admin panel, pour les profils qui ne sont pas super admin, préciser que l'édition des ressources n'est pas accessible : "votre profil ne nous permet pas d'éditer cette ressource" ou empêcher le double clic..

**Comment by dlacroix** [comment]
C'est sur laclasse-client et pas sur service-portail
