### ISSUE TITLE
Lien vers sites web externe

### ISSUE THREAD

**Issue by yamartin** [laclasse-com/service-portail#52]
Cela ne fonctionne pas d'ajouter un widget vers un site externe : exemple http://www.erasme.org

**Comment by cycojesus** [comment]
Les liens http:// sont changés en https:// par le portail sinon ils ne peuvent pas être ouverts dans l'iframe. Le certificat du site d'Erasme n'est pas accépté par le navigateur (chez moi)

**Comment by cycojesus** [comment]
désormais les liens externes s'ouvrent dans une nouvelle fenêtre/onglet
