### ISSUE TITLE
trombi, CCN et ressources numeriques ne s'affichent pas dans l'iframe

### ISSUE THREAD

**Issue by cycojesus** [laclasse-com/service-portail#55]
trouver une autre solution

**Comment by Pilooz** [comment]
Ne serait-ce pas un problème de http / https ?

**Comment by cycojesus** [comment]
je pense pas... je vais tout refactorer l'affichage des apps pour gérer les applis internes au portail mais ça va pas être immédiat :|

**Comment by Pilooz** [comment]
Oui, il y a du job si on compte :
- Les applis internes portail (pages statiques)
- Les applis internes Laclasse V3 mais externes portail
- Les applis externes
- Les liens urls externes

Pgl.

**Comment by cycojesus** [comment]
on peut aussi
