### ISSUE TITLE
question sur le flux sur le portail ipad2 v.8.1.2

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-portail#58]
"pas d'actu en affichage
en mode verticale
sinon oui en mode horizontal"
"il y a t il un nombre limité
de flux ? car il ne prend pas
compte de celui que j'ai rajouté
et en regardant de plus près
je viens de voir qu'il ne prend
aussi pas celui concernant
le Mag de Lyon"

**Comment by cycojesus** [comment]
> "pas d'actu en affichage
> en mode verticale
> sinon oui en mode horizontal"

C'est normal et voulu.

> "il y a t il un nombre limité
> de flux ? car il ne prend pas
> compte de celui que j'ai rajouté
> et en regardant de plus près
> je viens de voir qu'il ne prend
> aussi pas celui concernant
> le Mag de Lyon"

aujourd'hui le flux de Grand Lyon Mag fonctionne ainsi que celui du Monde. Le flux du Musée des Confluences fonctionne bien au'il soit vide.
