### ISSUE TITLE
Outil "manuels numériques" : un affichage sans picto

### ISSUE THREAD

**Issue by yamartin** [laclasse-com/service-portail#63]
On peut ajouter un outil manuel numérique qui n'a pas de logo mais le M seulement. 

![image](https://cloud.githubusercontent.com/assets/1089945/5903406/c1482e74-a581-11e4-86c8-e25e0cc0f23f.png)

**Comment by cycojesus** [comment]
C'est normal, cette application n'a pas d’icône définie (dans le fichier de configuration du portail). De fait c'est un doublon de l'application existante (id: GAR) qui elle a bien une icône (il s'agit du carré vert à gauche dans la copie d'écran.)
