### ISSUE TITLE
intégrer le logo de la Métropole.

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-portail#73]
Voir  où l'on pourrait le mettre sur la page de splash publique.
je pensais éventuellement à côté de celui du rhone ?
A la place ?

**Comment by heleroy** [comment]
à la place du logo Rhone vu qu'ils n'ont pas fait de convention pour utiliser notre ENT  pour la rentrée prochaine, que ce soit V2 ou V3... sauf si c'est quelque chose qui n'est pas encore tranché bien sûr...

**Comment by cmonnet** [comment]
Pour le moment il faut mettre les 2 (sur la V2 et la V3) vu qu'on est sur le maintien de service jusqu'à la fin de l'année scolaire. Ensuite le CG doit contacter la Métropole pour poursuivre l'utilisation de la V2 et les CCN sur l'année scolaire prochaine, dès qu'on a une validation on vous fais suivre.
Par contre je ne vois pas de quelle page tu parles, la mire d'authentification ?  la page de splash avec les modules activés ? sur celle là c'est pas évident de mettre les logos, pourtant il faudrait.
